ДЗ Микросетки на флексах
htmlacademy-htmlcss/2063947-sedona-34 pull request #6
Opened 2022-06-26 19:06 UTC by romanetsinna

2022-06-26 20:49 UTC, DoberBober commented on styles/styles.css
> +  padding-top: 30px;
Не то, чтобы ошибка, но тут больше маргин подходит. Всё таки это пространство между элементами.

2022-06-26 20:49 UTC, DoberBober commented on styles/styles.css
> +  height: 417px;
Сверху и снизу паддинги добавь.

2022-06-26 20:50 UTC, DoberBober commented on styles/styles.css
> +  padding: 91px 451px 29px 452px;
Сверху паддинг убери (это паддинг родительского блока). Слева и справа паддинги удалить (вместо них просто пропищи `text-align: center`), а снизу - паддинг замени на маргин (опять же, это пространство между элементами, а не часть заголовка).

2022-06-26 20:51 UTC, DoberBober commented on styles/styles.css
> +  padding-bottom: 68px;
Маргин. А ещё лучше будет, если ты тут удалишь этот отступ и сделаешь верхний маргин у ссылки, которая идёт дальше.

2022-06-26 20:52 UTC, DoberBober commented on styles/styles.css
> +  padding: 17px 150px;
Добавь `display: table` и `margin-left/right: auto`.

2022-06-26 20:54 UTC, DoberBober commented on styles/styles.css
> +  background-image: url("../images/index-background.jpg");
Картинку неправильно вырезала. Видишь, по краям и снизу есть отступы? Их не должно быть.
![image](https://user-images.githubusercontent.com/18398812/175833439-dd886629-a968-45a7-b05d-ff552fd4f3a7.png)

2022-06-26 20:54 UTC, DoberBober requested changes
Поправь замечания, допили внутреннюю и скидывай на повторную.
И иконки уже можешь подключить.

2022-06-27 02:14 UTC, romanetsinna commented on styles/styles.css
> +  padding: 91px 451px 29px 452px;
Исправила
text-align: center у меня указано в родительском элементе и это свойство наследуется здесь, т.е. я убрала паддинги слева и справа и ничего не изменилось

2022-06-27 02:21 UTC, romanetsinna commented on styles/styles.css
> +  padding-bottom: 68px;
Здесь отступ удалила, верхний маргин у ссылки добавила, но только после того, как обернула ссылку в div. 
Без div-а маргин не сработал у ссылки

2022-06-27 02:47 UTC, romanetsinna commented on styles/styles.css
> +  padding: 17px 150px;
Можно в двух словах - почему здесь стоит указать display: table ?

2022-06-27 03:47 UTC, romanetsinna commented
Замечания поправила, но что значит "допили внутреннюю"? Можно более конкретные замечания по странице каталога?
Я только что кое-что поправила (запушила), но сейчас не могу разобраться с карточками гостиниц и пагинацией + "Гостиниц на странице..."
Укажи, пожалуйста, хотя бы, что нужно сейчас исправить, а что - уже в следующих разделах.

Иконки, если можно, подключу позже, ведь впереди еще раздел "8. Декоративные элементы", а я сейчас пока на 6 разделе, буду делать все step by step

2022-06-27 06:32 UTC, DoberBober commented on styles/styles.css
> +  padding: 17px 150px;
Потому что ты паддинги прописываешь. У строчных элементов паддинги очень странно работают: они как бы и есть, но полноценно место не занимают.

2022-06-27 06:43 UTC, DoberBober commented
Думал, ты в каталоге раскидаешь по сторонам блоки в фильтре и оформишь карточки. В принципе, первое можешь сделать вместе с оформлением фильтров, когда будет лекция, а второе - на следующем задании.

А с чем разобраться не можешь помочь может?
(Отправляй на проверку, закрою текущее задание.)

2022-06-27 20:31 UTC, merged